services:
  psql-db:
    image: 'postgres:latest'
    container_name: psql-db
    restart: always
    environment:
      - 'POSTGRES_DB=rd_notification'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5782:5432'
  test:
    container_name: test-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8686:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/rd_notification
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - psql-db